

[module]
    [[module.mounts]]
        source = 'assets'
        target = 'assets'
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-integrationtests/commonmod2"

[params]
    name = "commonmod2"
